version: "3.9"
services:
  workers:
    build: .
    environment:
      SESSION: $SESSION_NAME
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      DATABASE_URL: $DATABASE_URL  # defaults to None
